export let mockStore = {
  user: {
    user: {
      _id: '7872916045974f82a3b51dd8ae9eece1',
      achievement: [],
      favourites: [],
      lastSelection: {
        selectedNote: '',
        selectedPlaylist: '',
      },
      recentPlaylist: [],
      token:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiTWF0dGVvIiwiZXhwIjoxNjU4NDAxOTQ0fQ.FtWhuipm1zA7rtL87NRQ5pwQsniNsAXpo5RPjmJKO2Y',
      userEmail: 'matteo@gmail.com',
      username: 'Matteo',
    },
    loading: false,
    error: false,
  },
  media: {
    data: {
      data: [
        {
          _id: 'b49a866d572d45f0bed20c43ea40884c',
          averageStars: {
            currentRating: 3.5,
            totalRatings: 2,
            totalStars: 7,
          },
          chapters: [
            {
              chapterId: 1,
              chapterTitle: 'HTML tags',
              end: '25.40',
              start: '20.24',
              text: 'What are some basic HTML (HyperText Markup Language) tags and how do you start writing HTML',
              uuid: 'c1db01dce06d4088b65b21as3536d81c',
              video_url: 'https://www.youtube.com/watch?v=qz0aGYrrlhU',
            },
            {
              chapterId: 2,
              chapterTitle: 'What is CSS',
              end: '01.15',
              start: '00.25',
              text: 'HTML (the Hypertext Markup Language) and CSS (Cascading Style Sheets) are two of the core technologies for building Web pages. HTML provides the structure of the page, CSS the (visual and aural) layout, for a variety of devices.',
              uuid: 'c1db01dce02d4088b65b21a43536d81c',
              video_url: 'https://www.youtube.com/watch?v=1PnVor36_40',
            },
            {
              chapterId: 3,
              chapterTitle: 'Javascript Summary',
              end: '02.35',
              start: '00.00',
              text: 'JavaScript is the the programming language that built the web. Learn how it evolved into a powerful tool for building websites, servers with Node.js, mobile apps, desktop software, and more.',
              uuid: 'c1db01dce02d4088b65b21a43536d8vc',
              video_url: 'https://www.youtube.com/watch?v=DHjqpvDnNGE',
            },
            {
              chapterId: 4,
              chapterTitle: 'Remote APIs',
              end: '17.03',
              start: '12.55',
              text: 'What is the benefit of using Remote APIs',
              uuid: 'c1db11dce02d4088b65b21a43536d8vc',
              video_url: 'https://www.youtube.com/watch?v=GZvSYJDk-us',
            },
            {
              chapterId: 5,
              chapterTitle: 'Software Testing',
              end: '06.00',
              start: '03.29',
              text: 'Software testing is defined as an activity to check whether the actual results match the expected results and to ensure that the software system is defect free.',
              uuid: '12db01dce02d4088b65b21a43536d8vc',
              video_url: 'https://www.youtube.com/watch?v=sO8eGL6SFsA',
            },
            {
              chapterId: 6,
              chapterTitle: 'React',
              end: '02.43',
              start: '00.57',
              text: 'What are the essentials that you need to know to start a react app?',
              uuid: 'c1db01dc202d4088b65b21a43536d8vc',
              video_url: 'https://www.youtube.com/watch?v=hQAHSlTtcmY',
            },
            {
              chapterId: 7,
              chapterTitle: 'Redux',
              end: '00.25',
              start: '00.17',
              text: 'Redux is a pattern and library that helps developers implement complex state management requirements at scale',
              uuid: 'c1db01dc702d4088b65b21a43536d8vc',
              video_url: 'https://www.youtube.com/watch?v=_shA5Xwe8_4',
            },
            {
              chapterId: 8,
              chapterTitle: 'Python Lists',
              end: '24.14',
              start: '17.40',
              text: 'Lists are used to store multiple items in a single variable.Lists are one of 4 built-in data types in Python used to store collections of data, the other 3 are Tuple, Set, and Dictionary, all with different qualities and usage.Lists are created using square brackets',
              uuid: 'c1db01dce02d4088b65b21a43536b8vc',
              video_url: 'https://www.youtube.com/watch?v=JJmcL1N2KQs&t=861s',
            },
            {
              chapterId: 9,
              chapterTitle: 'How do I use a Docker Container',
              end: '08.51',
              start: '7.12',
              text: 'Docker website with info on docker containers:https://www.docker.com/resources/what-container/',
              uuid: 'c1db01dce02d4n88b65b21a43536d8vc',
              video_url: 'https://www.youtube.com/watch?v=gAkwW2tuIqE',
            },
            {
              chapterId: 10,
              chapterTitle: 'Flask vs Django',
              end: '01.30',
              start: '00.00',
              text: 'Django, on the one hand, is a full-stack web framework, whereas Flask is a light-weight, extensible framework. If you want to dig more into coding and learn core concepts, Flask helps you understand how each component from the back-end works to get a simple web application up and running',
              uuid: 'c1db01dwe02d4088b65b21a43536d8vc',
              video_url: 'https://www.youtube.com/watch?v=3vfum74ggHE',
            },
          ],
          commentSection: [
            {
              comment: 'This playlist is great!',
              commentID: 1,
              thread: [
                {
                  reply: 'great indeed!',
                  timestamp: '00.00.00.10.05.22',
                  userEmail: 'gioele@gmail.com',
                  username: 'Gio',
                },
                {
                  reply: 'Looks great but I would add another section!',
                  timestamp: '00.00.00.10.05.22',
                  userEmail: 'igor@gmail.com',
                  username: 'Igor',
                },
              ],
              timestamp: '00.00.00.10.05.22',
              userEmail: 'matteo@gmail.com',
              username: 'Matteo',
            },
          ],
          editingAccess: ['gioele@gmail.com', 'igor@gmail.com'],
          playlistName: 'playlistX',
          playlistOwner: 'matteo@gmail.com',
          playlistTheme: '(0,0,0)',
          public: 'True',
          tags: ['tag1', 'tag2'],
          userStars: [
            {
              rating: 4,
              userEmail: 'gioele@gmail.com',
            },
            {
              rating: 3,
              userEmail: 'igor@gmail.com',
            },
          ],
        },
        {
          _id: 'b49a866d572d45f0bed20c43ea40884a',
          averageStars: {
            currentRating: 3,
            totalRatings: 2,
            totalStars: 6,
          },
          chapters: [
            {
              chapterId: 1,
              chapterTitle: 'first chapter',
              end: '0.30',
              start: '0.00',
              text: 'This is the section with the notes on the first chapter',
              uuid: 'c1dn01dce02d4088b65b21a43536d8vc',
              video_url: 'youtube.com',
            },
          ],
          commentSection: [
            {
              comment: 'This playlist is not amazing really',
              commentID: 1,
              thread: [
                {
                  reply: 'sucks indeed!',
                  timestamp: '00.00.00.10.05.22',
                  userEmail: 'gioele@gmail.com',
                  username: 'Gio',
                },
                {
                  reply: 'Looks great but I would add another section!',
                  timestamp: '00.00.00.10.05.22',
                  userEmail: 'igor@gmail.com',
                  username: 'Igor',
                },
              ],
              timestamp: '00.00.00.10.05.22',
              userEmail: 'matteo@gmail.com',
              username: 'Matteo',
            },
          ],
          editingAccess: [],
          playlistName: 'playlistY',
          playlistOwner: 'gio@gio.com',
          playlistTheme: '(0,0,0)',
          public: 'True',
          tags: ['tag1', 'tag2'],
          userStars: [
            {
              rating: 4,
              userEmail: 'gioele@gmail.com',
            },
            {
              rating: 2,
              userEmail: 'igor@gmail.com',
            },
          ],
        },
        {
          _id: 'b49a866d572d45f0bed20c43aa40884b',
          averageStars: {
            currentRating: 0,
            totalRatings: 0,
            totalStars: 0,
          },
          chapters: [
            {
              chapterId: 1,
              chapterTitle: 'HTML tags',
              end: '25.40',
              start: '20.24',
              text: 'What are some basic HTML (HyperText Markup Language) tags and how do you start writing HTML',
              uuid: 'c1db01dce02d4088b65b21a43b36d8vc',
              video_url: 'https://www.youtube.com/watch?v=qz0aGYrrlhU',
            },
          ],
          commentSection: [],
          editingAccess: [],
          playlistName: 'playlistM',
          playlistOwner: 'matteo@gmail.com',
          playlistTheme: '(0,0,0)',
          public: 'True',
          tags: [],
          userStars: [],
        },
        {
          _id: 'b49a866d572d45f0bed20s43ea40884b',
          averageStars: {
            currentRating: 0,
            totalRatings: 0,
            totalStars: 0,
          },
          chapters: [
            {
              chapterId: 1,
              chapterTitle: 'HTML tags',
              end: '25.40',
              start: '20.24',
              text: 'What are some basic HTML (HyperText Markup Language) tags and how do you start writing HTML',
              uuid: 'c1db01dce02d4s88b65b21a43536d8vc',
              video_url: 'https://www.youtube.com/watch?v=qz0aGYrrlhU',
            },
          ],
          commentSection: [],
          editingAccess: [],
          playlistName: 'playlistZ',
          playlistOwner: 'matteo@gmail.com',
          playlistTheme: '(0,0,0)',
          public: 'True',
          tags: [],
          userStars: [],
        },
        {
          _id: 'b49a866d572d45f0bed20c43ea40884b',
          averageStars: {
            currentRating: 0,
            totalRatings: 0,
            totalStars: 0,
          },
          chapters: [],
          commentSection: [],
          editingAccess: [],
          playlistName: 'emptyPlaylist',
          playlistOwner: 'igor@gmail.com',
          playlistTheme: '(0,0,0)',
          public: 'True',
          tags: [],
          userStars: [],
        },
      ],
      status: 200,
      statusText: 'OK',
      headers: {
        'content-length': '9202',
        'content-type': 'application/json',
      },
      config: {
        transitional: {
          silentJSONParsing: true,
          forcedJSONParsing: true,
          clarifyTimeoutError: false,
        },
        transformRequest: [null],
        transformResponse: [null],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
        env: {
          FormData: null,
        },
        headers: {
          Accept: 'application/json, text/plain, */*',
        },
        method: 'get',
        url: 'http://localhost:5000/playlist/trending',
      },
      request: {},
    },
    loading: false,
    error: false,
  },
  utube: {
    videos: [],
  },
  selection: {
    selected: '',
    startTime: 0,
    endTime: 0,
  },
}
